# Site settings
title: The Royal Fork
email: rf@royalforkblog.com
description: "A blog recording my journey down the Bitcoin rabbit hole."
baseurl: ""
url: "http://www.royalforkblog.com"
twitter_username: royalforkblog

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      layout: "post"
